In [3]:
import pandas as pd
import seaborn as sns


tips = sns.load_dataset('tips')
# tips.head()

URLError: <urlopen error [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1002)>

In [4]:
import statsmodels.formula.api as smf


model = smf.ols('tip ~ total_bill', data=tips)
results = model.fit()
results.summary()

ModuleNotFoundError: No module named 'statsmodels'

In [14]:
results.params

Intercept     0.920270
total_bill    0.105025
dtype: float64

In [15]:
from sklearn import linear_model

In [16]:
lr = linear_model.LinearRegression()

In [17]:
predicted = lr.fit(X=tips['total_bill'], y=tips['tip'])

ValueError: Expected 2D array, got 1D array instead:
array=[ 16.99  10.34  21.01  23.68  24.59  25.29   8.77  26.88  15.04  14.78
  10.27  35.26  15.42  18.43  14.83  21.58  10.33  16.29  16.97  20.65
  17.92  20.29  15.77  39.42  19.82  17.81  13.37  12.69  21.7   19.65
   9.55  18.35  15.06  20.69  17.78  24.06  16.31  16.93  18.69  31.27
  16.04  17.46  13.94   9.68  30.4   18.29  22.23  32.4   28.55  18.04
  12.54  10.29  34.81   9.94  25.56  19.49  38.01  26.41  11.24  48.27
  20.29  13.81  11.02  18.29  17.59  20.08  16.45   3.07  20.23  15.01
  12.02  17.07  26.86  25.28  14.73  10.51  17.92  27.2   22.76  17.29
  19.44  16.66  10.07  32.68  15.98  34.83  13.03  18.28  24.71  21.16
  28.97  22.49   5.75  16.32  22.75  40.17  27.28  12.03  21.01  12.46
  11.35  15.38  44.3   22.42  20.92  15.36  20.49  25.21  18.24  14.31  14.
   7.25  38.07  23.95  25.71  17.31  29.93  10.65  12.43  24.08  11.69
  13.42  14.26  15.95  12.48  29.8    8.52  14.52  11.38  22.82  19.08
  20.27  11.17  12.26  18.26   8.51  10.33  14.15  16.    13.16  17.47
  34.3   41.19  27.05  16.43   8.35  18.64  11.87   9.78   7.51  14.07
  13.13  17.26  24.55  19.77  29.85  48.17  25.    13.39  16.49  21.5
  12.66  16.21  13.81  17.51  24.52  20.76  31.71  10.59  10.63  50.81
  15.81   7.25  31.85  16.82  32.9   17.89  14.48   9.6   34.63  34.65
  23.33  45.35  23.17  40.55  20.69  20.9   30.46  18.15  23.1   15.69
  19.81  28.44  15.48  16.58   7.56  10.34  43.11  13.    13.51  18.71
  12.74  13.    16.4   20.53  16.47  26.59  38.73  24.27  12.76  30.06
  25.89  48.33  13.27  28.17  12.9   28.15  11.59   7.74  30.14  12.16
  13.42   8.58  15.98  13.42  16.27  10.09  20.45  13.28  22.12  24.01
  15.69  11.61  10.77  15.53  10.07  12.6   32.83  35.83  29.03  27.18
  22.67  17.82  18.78].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [18]:
predicted = lr.fit(X=tips['total_bill'].values.reshape(-1, 1),
                   y=tips['tip'])

In [19]:
predicted.coef_

array([ 0.10502452])

In [20]:
predicted.intercept_

0.92026961355467352

In [21]:
tips.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [22]:
model = smf.ols('tip ~ total_bill + sex', data=tips).fit()

In [23]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    tip   R-squared:                       0.457
Model:                            OLS   Adj. R-squared:                  0.452
Method:                 Least Squares   F-statistic:                     101.3
Date:                Fri, 11 May 2018   Prob (F-statistic):           1.18e-32
Time:                        18:20:35   Log-Likelihood:                -350.52
No. Observations:                 244   AIC:                             707.0
Df Residuals:                     241   BIC:                             717.5
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept         0.9067      0.175      5.182      0.000       0.562       1.251
sex[T.Female]     0.0266      0.138      0.192      0.848      -0.246       0.299
total_bill        0.1052      0.007     14.110      0.000       0.091       0.120
==============================================================================
Omnibus:                       20.499   Durbin-Watson:                   2.149
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               38.652
Skew:                           0.447   Prob(JB):                     4.05e-09
Kurtosis:                       4.733   Cond. No.                         63.0
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [24]:
lr = linear_model.LinearRegression()

In [25]:
predicted = lr.fit(tips[['total_bill', 'sex']], tips['tip'])

ValueError: could not convert string to float: 'Female'

In [26]:
tips_dummy = pd.get_dummies(tips[['total_bill', 'sex', 'tip']])

In [27]:
tips_dummy.head()

total_bill   tip  sex_Male  sex_Female
0       16.99  1.01         0           1
1       10.34  1.66         1           0
2       21.01  3.50         1           0
3       23.68  3.31         1           0
4       24.59  3.61         0           1

In [28]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
total_bill    244 non-null float64
tip           244 non-null float64
sex           244 non-null category
smoker        244 non-null category
day           244 non-null category
time          244 non-null category
size          244 non-null int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.2 KB


In [29]:
tips_dummy = pd.get_dummies(tips[['tip', 'total_bill', 'sex']], drop_first=True)
tips_dummy.head()

tip  total_bill  sex_Female
0  1.01       16.99           1
1  1.66       10.34           0
2  3.50       21.01           0
3  3.31       23.68           0
4  3.61       24.59           1

In [30]:
predicted = lr.fit(tips_dummy.iloc[:, 1:], tips_dummy['tip'])

In [31]:
predicted.coef_

array([ 0.10523236,  0.02660871])

In [33]:
tips_dummy.head()

tip  total_bill  sex_Female
0  1.01       16.99           1
1  1.66       10.34           0
2  3.50       21.01           0
3  3.31       23.68           0
4  3.61       24.59           1

In [34]:
from patsy import dmatrices

In [35]:
response, predictors = dmatrices('tip ~ total_bill + sex', data = tips)

In [38]:
#response

In [39]:
#predictors

In [40]:
predicted = lr.fit(predictors, response)

In [41]:
predicted.coef_

array([[ 0.        ,  0.02660871,  0.10523236]])